const data=[
{id:1,img:"assets/pwc-india.png",title:"PwC India Corporate Website",tag:"AEM · ENTERPRISE",cats:["aem"],tech:"AEM · HTML5 · CSS3 · JavaScript · jQuery · Bootstrap",summary:"Created and revamped pages using AEM components, templates and content fragments. Built responsive campaign, service and industry layouts and supported large content releases.",detail:"Worked on an ongoing PwC India corporate website engagement, including AEM authoring, reusable components, page properties, metadata, OG tags, content dumps, DAM assets, cross-browser testing and production validation.",role:"Web Developer",result:"Responsive enterprise publishing and production support"},
{id:2,img:"assets/toruscope.png",title:"Toruscope",tag:"WORDPRESS · SEO",cats:["wordpress","php"],tech:"WordPress · PHP · MySQL · HTML5 · CSS3 · JavaScript",summary:"Converted Figma designs into a responsive WordPress blog with dynamic templates, category/listing/single-post views, web stories, SEO, caching and image optimisation.",detail:"Built reusable content modules with custom fields and WP_Query-driven sections, implemented pagination and dynamic content loading, integrated MakeStories.io and handled post-launch maintenance.",role:"Web Developer",result:"Client-editable blog platform with performance and SEO work"},
{id:3,img:"assets/raipur-green-energy.png",title:"Raipur Green Energy",tag:"PHP · MYSQL · AJAX",cats:["wordpress","php"],tech:"WordPress · PHP · MySQL · REST API · AJAX · JSON",summary:"Corporate WordPress site with custom agent registration/login, role-based access, REST API vehicle lookup and an admin approval workflow.",detail:"Built custom PHP/MySQL authentication outside the standard WordPress user flow, integrated a third-party vehicle REST API, handled validation and secure password storage, and created agent-management administration.",role:"Web Developer",result:"Custom agent portal and API-driven vehicle lookup"},
{id:4,img:"assets/soulfoods.png",title:"Soulfoods",tag:"SHOPIFY · E-COMMERCE",cats:["shopify"],tech:"Shopify · Liquid · HTML5 · CSS3 · JavaScript · jQuery",summary:"Maintained and enhanced an existing Shopify storefront, including Liquid templates, product/collection/cart changes and dynamic variant pricing and image switching.",detail:"Implemented multiple pack-size and jar-size purchase options using Shopify variants, updated product and cart templates, and resolved responsive and cross-browser storefront defects.",role:"Web Developer",result:"Ongoing e-commerce maintenance and enhancements"},
{id:5,img:"assets/pricewaterhouse.png",title:"Pricewaterhouse.in Microsite",tag:"AEM · FIGMA",cats:["aem"],tech:"Figma · AEM · HTML5 · CSS3 · JavaScript · jQuery",summary:"Converted an approved Figma design into pixel-accurate responsive AEM templates and customised header/footer behaviour.",detail:"Implemented semantic markup, heading hierarchy and on-page SEO structure, optimised images/scripts/stylesheets and supported UAT fixes, go-live activities and post-launch content updates.",role:"Web Developer",result:"Responsive AEM microsite from approved design"},
{id:6,img:"assets/mandaala.png",title:"Mandaala",tag:"WORDPRESS · RESPONSIVE",cats:["wordpress"],tech:"WordPress · HTML5 · CSS3 · JavaScript · Responsive Design",summary:"Developed and maintained a responsive WordPress website with reusable content structures and frontend enhancements.",detail:"Worked on responsive WordPress implementation, content layouts, frontend styling and ongoing maintenance while keeping the site aligned with approved designs and content requirements.",role:"Web Developer",result:"Responsive WordPress website implementation"},
{id:7,img:"assets/fab-habitat.png",title:"Fab Habitat",tag:"SHOPIFY · STOREFRONT",cats:["shopify"],tech:"Shopify · Liquid · HTML5 · CSS3 · JavaScript",summary:"Worked on a Shopify storefront with responsive UI improvements, theme-level customisation and e-commerce frontend maintenance.",detail:"Handled Shopify theme customisation, responsive frontend changes and storefront maintenance across product and content areas.",role:"Web Developer",result:"Responsive Shopify storefront enhancements"},
{id:8,img:"assets/sydler.png",title:"Sydler India",tag:"WORDPRESS · WEB DEVELOPMENT",cats:["wordpress"],tech:"WordPress · HTML5 · CSS3 · JavaScript · Responsive Design",summary:"Built and maintained a responsive corporate website with frontend implementation and content-driven sections.",detail:"Worked on frontend implementation, responsive layouts, content sections and ongoing maintenance for the corporate website.",role:"Web Developer",result:"Responsive corporate website delivery"}
];

const grid=document.getElementById("projectgrid");
function renderProjects(filter="all"){
 const items=data.filter(x=>filter==="all"||x.cats.includes(filter));
 grid.innerHTML=items.map((p,i)=>`<article class="project ${i===0&&filter==="all"?"featured":""}" tabindex="0" data-id="${p.id}" aria-label="Open ${p.title}"><div class="project-image"><img src="${p.img}" alt="${p.title} website screenshot" loading="lazy"><span class="project-index">${String(p.id).padStart(2,"0")}</span><span class="project-arrow">↗</span></div><div class="project-info"><div class="tag">${p.tag}</div><h3>${p.title}</h3><p>${p.summary}</p><div class="chips">${p.tech.split(" · ").slice(0,4).map(t=>`<span>${t}</span>`).join("")}</div></div></article>`).join("");
 grid.querySelectorAll(".project").forEach(card=>{card.addEventListener("click",()=>openProject(+card.dataset.id));card.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();openProject(+card.dataset.id)}})});
}
renderProjects();
document.querySelectorAll(".filter").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderProjects(b.dataset.filter)}));

const modal=document.getElementById("modal"), modalContent=document.getElementById("modalContent");
function openProject(id){const p=data.find(x=>x.id===id);if(!p)return;modalContent.innerHTML=`<img class="modalimage" src="${p.img}" alt="${p.title} website screenshot"><div class="modaltag">${p.tag}</div><h2 id="modalTitle">${p.title}</h2><p>${p.detail}</p><div class="modalmeta"><div><strong>Role</strong><span>${p.role}</span></div><div><strong>Technologies</strong><span>${p.tech}</span></div><div><strong>Project focus</strong><span>${p.result}</span></div></div>`;modal.classList.add("show");modal.setAttribute("aria-hidden","false");document.getElementById("close").focus();document.body.classList.add("modal-open")}
function closeModal(){modal.classList.remove("show");modal.setAttribute("aria-hidden","true");document.body.classList.remove("modal-open")}
document.getElementById("close").addEventListener("click",closeModal);modal.addEventListener("click",e=>{if(e.target===modal)closeModal()});document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});

const nav=document.getElementById("nav");document.getElementById("menu").addEventListener("click",()=>nav.classList.toggle("open"));document.querySelectorAll("#navlinks a").forEach(a=>a.addEventListener("click",()=>nav.classList.remove("open")));
window.addEventListener("scroll",()=>{const h=document.documentElement.scrollHeight-innerHeight;document.getElementById("progress").style.width=(h>0?(scrollY/h)*100:0)+"%"},{passive:true});

const revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add("visible")}),{threshold:.12});document.querySelectorAll(".section,.project,.skill-grid article,.timeline article").forEach(el=>{el.classList.add("reveal");revealObserver.observe(el)});
